### ISSUE TITLE
progress support

### ISSUE THREAD

**Issue by renmu123** [nurrony/hlsdownloader#147]
## Prerequisites

- [x] Can you reproduce the problem in safe mode?
- [x] Are you running the latest version?
- [x] Did you perform a cursory search?

### Description

When l download file, l want to get the live progress like:
```js
const downloader = new HLSDownloader({});
downloader.startDownload();

downloader.on("progress",()=>{
// update ui
})
downloader.on("completed",()=>{
// do something
})
```

**Comment by nurrony** [comment]
@renmu123, HLSDownloader do support download progress via Ky's `onDownloadProgress` hook. does it cover your use cases. It is not yet support `completed` event hook. Could you please explain  what you are trying to achieve?

**Comment by renmu123** [comment]
I am building a command-line video downloader for a specific website where the m3u8 file contains over 1000 parts. I want to know the proportion of completed parts to the overall total."

**Comment by nurrony** [comment]
@renmu123 You can check now pass a `onData` hook function like below 
```js
const downloader = new HLSDownloader({
  onData: (data) => {
     console.info(`Downloaded ${data.item} in ${data.path}. Total items to download = ${data.total}` );
  }
})
```
please give your feedback on the API.

I am working on `onError` hook as well. Please check this issue #152 for more details

**Comment by nurrony** [comment]
@renmu123 please check this PR for onError Hook as well. Hope it covers all your use cases https://github.com/nurrony/hlsdownloader/pull/156

**Comment by renmu123** [comment]
Thanks for you help, l have tested the progress feature, it can meet the needs

**Comment by nurrony** [comment]
> Thanks for you help, l have tested the progress feature, it can meet the needs

Lovely! Happy to Help
